BMLT Root Server: /home/travis/build/bmlt-enabled/bmlt-root-server/main_server/client_interface/html/config-bmlt-basic.inc.php File Reference
config-bmlt-basic.inc.php File Reference
Variables
$config_file_path = dirname(dirname(dirname(__FILE__))).'/server/config/get-config.php'
if (file_exists($config_file_path))
$server = c_comdef_server::MakeServer()
Variable Documentation
$config_file_path = dirname(dirname(dirname(__FILE__))).'/server/config/get-config.php'
This file is part of the Basic Meeting List Toolbox (BMLT). *
Find out more at: https://bmlt.app *
BMLT is free software: you can redistribute it and/or modify * it under the terms of the MIT License. *
BMLT is distributed in the hope that it will be useful, * but WITHOUT ANY WARRANTY; without even the implied warranty of * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the * MIT License for more details. *
You should have received a copy of the MIT License along with this code. * If not, see https://opensource.org/licenses/MIT. *
Definition at line 21 of file config-bmlt-basic.inc.php.
Referenced by GetServerInfo().
$server = c_comdef_server::MakeServer()
Definition at line 33 of file config-bmlt-basic.inc.php.
Referenced by BMLT_FuncNAWSReturnDirections(), BMLT_FuncNAWSReturnFormat1(), BMLT_FuncNAWSReturnFormat2(), BMLT_FuncNAWSReturnFormat3(), BMLT_FuncNAWSReturnFormat4(), BMLT_FuncNAWSReturnFormat5(), BMLT_FuncNAWSReturnLanguage1(), BMLT_FuncNAWSReturnLastMeetingChangeTime(), BMLT_FuncNAWSReturnMeetingNAWSID(), BMLT_FuncNAWSReturnMeetingServiceBodyName(), BMLT_FuncNAWSReturnMeetingServiceBodyNAWSID(), BMLT_FuncNAWSReturnMeetingTown(), BMLT_FuncNAWSReturnNonNawsFormats(), BMLT_FuncNAWSReturnOpenOrClosed(), BMLT_FuncNAWSReturnPublishedStatus(), BMLT_FuncNAWSReturnTime(), BMLT_FuncNAWSReturnWeekday(), BMLT_FuncNAWSReturnWheelchair(), bmlt_populate_format_dictionary(), c_comdef_admin_bar(), dropEverything(), GetChildServiceBodies(), GetFormats(), c_comdef_server\GetLocalStrings(), GetServiceBodies(), c_comdef_server\GetServiceBodyByIDObj(), c_comdef_server\GetServiceBodyHierarchyIDs(), c_comdef_service_body\IsOwnedBy(), parse_redirect(), c_comdef_admin_xml_handler\process_meeting_search(), ReturnNAWSDeletedMeetings(), ReturnNAWSFormatCSV(), and c_comdef_user\SetNewPassword().
if
Initial value:
{
        require_once(dirname(__FILE__).'/../server_admin/lang/en/install_wizard_strings.php')
Uncomment this for debug mode. We scan through the "lang" directory, and pick out the available localizations. These will be kept in the comdef_global_languages array.
Definition at line 23 of file config-bmlt-basic.inc.php.